# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
puts "🌱 Seeding data..."
puts "Deleting old data..."

UserAdmin.destroy_all
Villa.destroy_all
Activity.destroy_all
Location.destroy_all
Inquiry.destroy_all


u1 = UserAdmin.create!(first_name: "Janice", last_name: "Alecha", password: "adminjanz", email:"janiceralecha@gmail.com", phone: 832-814-6203, admin: true)
u2 = UserAdmin.create!(first_name: "Genevieve", last_name: "Lopez", password: "admingen", email:"genlopez05@gmail.com", phone: 713-829-4351, admin: true)
u3 = UserAdmin.create!(first_name: "Claire", last_name: "Smith", password: "adminclaire", email:"clairesmith95@gmail.com", phone: 631-789-4262, admin: true)
u4 = UserAdmin.create!(first_name: "Jessa", last_name: "Stone", password: "adminjess", email:"jessastone00@gmail.com", phone: 607-333-7145, admin: true)

l1 = Location.create!(city: "Guanacaste", country: "Costa Rica", image: "https://media.cntraveller.com/photos/611bf67d3e186825295c3365/16:9/w_2560%2Cc_limit/Aerial-32-Manuel-Antonio.jpg", description: "Guanacaste, a province in northwestern Costa Rica bordering the Pacific, is known for its beaches and biodiverse parkland. Its Santa Rosa National Park is home to rare dry tropical forest, surfing sites and some 250 bird species. Endless beaches include Playa Blanca, with its calm waters, and Playa Hermosa, popular for diving and water sports. Papagayo Peninsula hosts luxury resorts and golf courses.")
l2 = Location.create!(city: "Loire Valley", country: "France", image: "https://cdn.britannica.com/87/687-050-06103996/chateau-Villandry-gardens-Tours-France-Loire-Valley-1532.jpg", description: "The Loire Valley, spanning 280 kilometres, is a valley located in the middle stretch of the Loire river in central France, in both the administrative regions Pays de la Loire and Centre-Val de Loire. The area of the Loire Valley comprises about 800 square kilometres.")
l3 = Location.create!(city: "Santorini", country: "Greece", image: "https://www.gannett-cdn.com/presto/2021/06/10/USAT/3d0222f3-5ccd-4e21-ab70-803ce1badd16-GettyImages-510967662.jpg?crop=2120%2C1193%2Cx0%2Cy211&width=1200", description: "Santorini is one of the Cyclades islands in the Aegean Sea. It was devastated by a volcanic eruption in the 16th century BC, forever shaping its rugged landscape. The whitewashed, cubiform houses of its 2 principal towns, Fira and Oia, cling to cliffs above an underwater caldera. They overlook the sea, small islands to the west and beaches made up of black, red and white lava pebbles.")
l4 = Location.create!(city: "Montego Bay", country: "Jamaica", image: "https://images.contentstack.io/v3/assets/blt00454ccee8f8fe6b/blt03acfca6197d45cc/61bae74bd73c783f9a3d1a6a/US_MontegoBay_JM_Headerjpg.jpg", description: "Montego Bay, the capital of Saint James Parish on Jamaicas north coast, is a major cruise ship port with numerous beach resorts and golf courses outside its commercial core. Popular beaches include Doctors Cave Beach and Walter Fletcher Beach, home to an amusement park. There is also snorkelling and diving at coral reefs in the protected waters of Montego Bay Marine Park.")
l5 = Location.create!(city: "Raa Atoll", country: "Maldives", image: "https://www.luxurylifestylemag.co.uk/wp-content/uploads/2023/01/DJI_0106-copy.jpg", description: "Raa Atoll is a small island in the Indian Ocean, located in the Indian Ocean, near the Arabian Sea. Amongst the soft and hard corals you will find nudibranchs, colorful sponges, elaborate sea fans, crustaceans and octopus.")
l6 = Location.create!(city: "Koh Yao Noi", country: "Thailand", image: "https://mediaim.expedia.com/destination/1/02ae3e9cbf359c0b3d6eca28839d4f7a.jpg", description: "Ko Yao Yai is a Thai island in the Andaman Sea, halfway between Phuket and Krabi. Its characterized by sandy shores, mangroves, rubber plantations and fishing villages. Beaches include Loh Paret and Loh Jark, the latter with a pier for ferries and long-tail boats. The surrounding waters are rich in coral and dotted with dive sites, like the King Cruiser Wreck near Anemone Reef, and the pinnacles of Shark Point.")
l7 = Location.create!(city: "Cabo San Lucas", country: "Mexico", image: "https://youimg1.tripcdn.com/target/100214000000wcrs0EF64.jpg?proc=source%2Ftrip", description: "Cabo San Lucas, a resort city on the southern tip of Mexicos Baja California peninsula, is known for its beaches, water-based activities and nightlife. Playa El Médano is Cabos main beach, with outdoor restaurants and numerous bars. Past the marina is Lands End promontory, site of Playa del Amor and El Arco, a natural archway in the seacliffs.")
l8 = Location.create!(city: "Aspen", country: "USA", image: "https://www.mensjournal.com/.image/c_limit%2Ccs_srgb%2Cq_auto:good%2Cw_700/MTk2MTM3MTU2NDI3MjYxNDQ1/aspen.webp", description: "Aspen, in Colorados Rocky Mountains, is a ski resort town and year-round destination for outdoor recreation. It is also known for high-end restaurants and boutiques, and landmarks like the Wheeler Opera House, built in 1889 during the areas silver mining boom. The Wheeler-Stallard House is a local history museum set in a 19th-century, Queen Anne–style home, while the Aspen Art Museum displays contemporary artworks.")
l9 = Location.create!(city: "Punta Cana", country: "Dominican Republic", image: "https://a.cdn-hotels.com/gdcs/production6/d1070/34764894-f30f-4db9-9ef9-ef07baf7e2fd.jpg", description: "Punta Cana, the easternmost tip of the Dominican Republic, abuts the Caribbean Sea and the Atlantic Ocean. It is the capital of the Caribbean Sea, as a region known for its 32km stretch of beaches and clear waters. The Bavaro area and Punta Cana combine to form whats known as La Costa del Coco, or the Coconut Coast, an area of lavish, all-inclusive resorts. Its popular for zip-lining, windsurfing, kayaking and sailing.")
l10 = Location.create!(city: "El Nido", country: "Philippines", image: "https://mediaim.expedia.com/destination/1/dcc4b5ab1c594fa368c2c71f52313040.jpg", description: "El Nido is a Philippine municipality on Palawan island. It is known for white-sand beaches, coral reefs and as the gateway to the Bacuit archipelago, a group of islands with steep karst cliffs. Miniloc Island is famed for the clear waters of its Small and Big lagoons. Nearby Shimizu Island has fish-filled waters. The area has many dive sites, including Dilumacad Island, which is long tunnel leading to an underwater cavern.")
l11 = Location.create!(city: "Lautoka", country: "Fiji", image: "https://www.theknot.com/tk-media/images/f323e3d9-729b-4776-bbe7-bea8a0198411", description: "Fiji, a country in the South Pacific, is an archipelago of more than 300 islands. It is famed for rugged landscapes, palm-lined beaches and coral reefs with clear lagoons. Its major islands, Viti Levu and Vanua Levu, contain most of the population. Viti Levu is home to the capital, Suva, a port city with British colonial architecture. The Fiji Museum, in the Victorian-era Thurston Gardens, has ethnographic exhibits.")
l12 = Location.create!(city: "Tulum", country: "Mexico", image: "https://media.cntraveler.com/photos/546cd38c2a3d21fa285c8069/16:9/w_2580,c_limit/el-castillo-quintana-roo-tulum-mexico.jpg", description: "Tulum is a town on the Caribbean coastline of Mexicos Yucatan, located in the Pacific Ocean Peninsula. It is known for its beaches and well-preserved ruins of an ancient Mayan port city. The main building is a large stone structure called El Castillo, perched on a rocky cliff above the white sand beach and turquoise sea. Near the ruins is the Parque Nacional Tulum, a coastal area with mangroves and cenotes")
l13 = Location.create!(city: "Oahu", country: "USA", image: "https://cdn.aarp.net/content/dam/aarp/travel/Domestic/2021/12/1140-oahu-hero.jpg", description: "Oahu is a U.S. island in the Central Pacific, part of the Hawaiian island chain and home to the state capital, Honolulu. Highlights of the city include historic Chinatown and the Punchbowl, a crater-turned-cemetery. Waikiki is an iconic beach, dining and nightlife area. West of Honolulu is Pearl Harbor, site of the WWIIs 1941 bombing attack and home to the USS Arizona Memorial. ")
l14 = Location.create!(city: "Sicily", country: "Italy", image: "https://www.wendyperrin.com/wp-content/uploads/2018/06/stock-photo-mountain-village-novara-di-sicilia-sicily-italy-shutterstock_736870174.jpg", description: "Sicily, the largest Mediterranean island, is just off the toe of Italys boot. Its rich history is reflected in sites like the Valley of the Temples, the well-preserved ruins of 7 monumental, Doric-style Greek temples, and in the Byzantine mosaics at the Cappella Palatina, a former royal chapel in capital city Palermo. On Sicily’s eastern edge is Mount Etna, one of Europe’s highest active volcanoes.")
l15 = Location.create!(city: "Big Sky", country: "USA", image: "https://www.visitbigsky.com/sites/default/files/styles/scale_1440/public/2021-04/The%20Meadow.jpg?itok=3utDx7Bp", description: "Big Sky is a community in the Rocky Mountains of southern Montana. It is known for the ski and downhill mountain-bike trails of Big Sky Resort. Southeast of town is Yellowstone National Park, with its wildlife, hot springs and gushing geysers. To the northeast, the choppy Gallatin River cuts through the rugged Gallatin Canyon. On a tributary, Ousel Falls Park has a waterfall, picnic areas and viewpoints.")
l16 = Location.create!(city: "Faro", country: "Portugal", image: "https://www.iberian-escapes.com/images/faro-algarve-portugal.jpg", description: "Faro is the capital of southern Portugal Algarve region. The city is bordered by the towns of the Arco da Vila and the Algarve. The neoclassical Arco da Vila is on the site of a gate that was part of the original Moorish wall. The monumental archway leads to the old town, with its cobbled streets. Nearby is Faro Cathedral, built in the 13th century. The Municipal Museum, in a 16th-century convent, displays prehistoric and medieval artifacts, plus religious art.")
l17 = Location.create!(city: "Tortola", country: "British Virgin Islands", image: "https://cruisethewaves.com/wp-content/uploads/2021/02/Road-Town-Tortola-British-Virgin-Islands7.jpg", description: "Tortola is the largest of the British Virgin Islands in the Caribbean. It features several white-sand beaches, including Cane Garden Bay and Smugglers Cove. Road Town, the capital of the British Virgin Islands, has a harbor dotted with sailing boats and is known as a yachting hub. In the islands southwest, forested Sage Mountain National Park offers trails and sweeping views over neighboring cays.")
l18 = Location.create!(city: "Ibiza", country: "Spain", image: "https://image.cnbcfm.com/api/v1/image/107085623-1657201218424-gettyimages-1278660829-dji_0569.jpeg?v=1658113863", description: "Ibiza is one of the Balearic islands, an archipelago of Spain in the Mediterranean Sea. It is well known for the lively nightlife in Ibiza Town and Sant Antoni, where major European nightclubs have summer outposts. It is also home to quiet villages, yoga retreats and beaches, from Platja den Bossa, lined with hotels, bars and shops, to quieter sandy coves backed by pine-clad hills found all around the coast.")
l19 = Location.create!(city: "Malibu", country: "USA", image: "https://assets.savills.com/properties/US0001S27682/01_l_gal.jpg", description: "Malibu is a city west of Los Angeles, California. It is known for its celebrity homes and beaches, including wide and sandy Zuma Beach. To the east is Malibu Lagoon State Beach, known as Surfrider Beach for its waves. Nearby is the Spanish Revival–style Adamson House, with local history displays in its Malibu Lagoon Museum. Inland, trails weave through canyons, waterfalls and grasslands in the Santa Monica Mountains.")
l20 = Location.create!(city: "Dangriga", country: "Belize", image: "https://w4x5t4z2.stackpathcdn.com/wp-content/uploads/2015/08/Belize-Wildlife-Holidays_Accommodation_Pelicans-South-Water-Caye.jpg", description: "Dangriga, formerly known as Stann Creek Town, is a town in southern Belize, located on the Caribbean coast at the mouth of the North Stann Creek River. It is the capital of Belize and the largest city in the Stann Creek District. Dangriga is served by the Dangriga Airport. ")
l21 = Location.create!(city: "Dubrovnik", country: "Croatia", image: "https://lp-cms-production.imgix.net/2021-06/shutterstockRF_662032261.jpg?auto=format&w=1440&h=810&fit=crop&q=75", description: "Dubrovnik is a city in southern Croatia fronting the Adriatic Sea. It is known for its distinctive Old Town, encircled with massive stone walls completed in the 16th century. Its well-preserved buildings range from baroque St. Blaise Church to Renaissance Sponza Palace and Gothic Rectors Palace, now a history museum. Paved with limestone, the pedestrianized Stradun is lined with shops and restaurants.")
l2 = Location.create!(city: "Geneva", country: "Switzerland", image: "https://deih43ym53wif.cloudfront.net/bern-switzerland-shutterstock_1845136612.jpg_ecb4c93750.jpg", description: "Geneva is a city in Switzerland that lies at the southern tip of expansive Lac Léman. Surrounded by the Alps and Jura mountains, the city has views of dramatic Mont Blanc. Headquarters of Europes United Nations and the Red Cross, it is a global hub for diplomacy and banking. French influence is widespread, from the language to gastronomy and bohemian districts like Carouge.")
l2 = Location.create!(city: "Franschhoek", country: "France", image: "https://aws-tiqets-cdn.imgix.net/images/content/7b66f5b1fa3a4bc1aca955477d11e3a9.jpg?auto=format&fit=crop&ixlib=python-3.2.1&q=70&s=a6a9214e386b43cde33a74975e3c882d", description: "Franschhoek is a town in South Africa, located in the north of the Cape of Good Hopes Western Cape with centuries-old vineyards and Cape Dutch architecture. Trails wind through flowers and wildlife at Mont Rochelle Nature Reserve to views over Franschhoek Valley. The Huguenot Memorial Museum and neighboring monument honor the areas French settlers, who arrived in the 17th and 18th centuries. Franschhoek Motor Museum displays vintage cars amid mountain farmland.")
l2 = Location.create!(city: "Puerto Vallarta", country: "Mexico", image: "https://www.libertytravel.com/sites/default/files/styles/full_size/public/lt_mar8_puerto_vallarta_lt-blog-main-1920x1080.jpg?itok=JMhT1vZ9", description: "Puerto Vallarta is a resort town on Mexico located in the south-eastern parts Pacific coast, in Jalisco state. It is known for its beaches, water sports and nightlife scene. Its cobblestone center is home to the ornate Nuestra Señora de Guadalupe church, boutique shops and a range of restaurants and bars. El Malecón is a beachside promenade with contemporary sculptures, as well as bars, lounges and nightclubs.")